/* eslint-disable @next/next/no-page-custom-font */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CatEyes from '../components/CatEyes'
import Slider from '../components/Slider'

export default function Home({facts}) {
  return (
    <div>
      <Head>
        <title>Did you know?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Palanquin:wght@300;400&display=swap" rel="stylesheet" />
      </Head>

      <main>
        <CatEyes />
        <Slider facts={facts}/>
      </main>

      <footer>
      </footer>
    </div>
  )
}

export async function getStaticProps(context) {
  const res = await fetch('https://catfact.ninja/facts?limit=20', { method: 'GET' })
	const json = await res.json()
  const facts = await json.data

	return {
		props: {
			facts,
		},
	}
}